# Generated by Django 3.0.8 on 2020-08-04 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FUNCIONARIO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NOM_FUNCIO', models.CharField(max_length=100)),
                ('DCR_CARGO_FUNCIO', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PRODUTO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NOM_PRODUT', models.CharField(max_length=100)),
                ('IMG_PRODUT', models.ImageField(upload_to='images')),
                ('DAT_PRODUT', models.DateField(verbose_name='Data de Atualização')),
                ('VLR_PRODUT', models.FloatField()),
                ('QTD_PRODUT', models.FloatField()),
                ('DCR_MODELO_PRODUT', models.CharField(max_length=50)),
                ('DCR_FABRIC_PRODUT', models.CharField(max_length=50)),
                ('MRC_PRDSRV_PRODUT', models.CharField(choices=[('produto', 'Produto'), ('serviço', 'serviço')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='OBRA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NOM_OBRA', models.CharField(max_length=100)),
                ('IMG_OBRA', models.ImageField(null=True, upload_to='images')),
                ('NOM_CLIENT_OBRA', models.CharField(max_length=70)),
                ('DAT_OBRA', models.DateField(verbose_name='Data de início')),
                ('NOM_FNCRSP_OBRA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.FUNCIONARIO')),
            ],
        ),
        migrations.CreateModel(
            name='ITEM_OBRA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QTD_ITMOBR', models.FloatField()),
                ('DCR_OBSERV_ITMOBR', models.CharField(max_length=50)),
                ('NOMEOBRA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.OBRA')),
                ('NOMEPRODUTO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.PRODUTO')),
            ],
        ),
    ]
