# Generated by Django 3.0.8 on 2020-08-04 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='DCR_CARGO_FUNCIO',
            field=models.CharField(max_length=50, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='NOM_FUNCIO',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='item_obra',
            name='DCR_OBSERV_ITMOBR',
            field=models.CharField(max_length=50, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='item_obra',
            name='NOMEOBRA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.OBRA', verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='item_obra',
            name='NOMEPRODUTO',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.PRODUTO', verbose_name='Produto'),
        ),
        migrations.AlterField(
            model_name='item_obra',
            name='QTD_ITMOBR',
            field=models.FloatField(verbose_name='Qtd. Aplicada'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='IMG_OBRA',
            field=models.ImageField(null=True, upload_to='images', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='NOM_CLIENT_OBRA',
            field=models.CharField(max_length=70, verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='NOM_FNCRSP_OBRA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.FUNCIONARIO', verbose_name='Responsável'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='NOM_OBRA',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='DCR_FABRIC_PRODUT',
            field=models.CharField(max_length=50, verbose_name='Fabricante'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='DCR_MODELO_PRODUT',
            field=models.CharField(max_length=50, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='IMG_PRODUT',
            field=models.ImageField(upload_to='images', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='MRC_PRDSRV_PRODUT',
            field=models.CharField(choices=[('produto', 'Produto'), ('serviço', 'serviço')], max_length=20, verbose_name='Classificação'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='NOM_PRODUT',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='QTD_PRODUT',
            field=models.FloatField(verbose_name='Qtd. em estoque'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='VLR_PRODUT',
            field=models.FloatField(verbose_name='Valor Unit.'),
        ),
    ]
